"use client";
import React from "react";
import * as _Builtin from "./_Builtin";
import { IconArrow } from "./IconArrow";
import { IconSearch } from "./IconSearch";
import { ButtonMain } from "./ButtonMain";
import * as _utils from "./utils";
import _styles from "./Menu.module.css";

export function Menu({ as: _Component = _Builtin.Block, variant = "Mobile" }) {
  const _styleVariantMap = {
    Mobile: "",
    Desktop: "w-variant-23049969-09ac-2789-520b-3c6ae895bbc6",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <_Component
      className={_utils.cx(_styles, "nav_links_component", _activeStyleVariant)}
      tag="nav"
      aria-label="Main"
    >
      <_Builtin.List
        className={_utils.cx(_styles, "nav_links_wrap", _activeStyleVariant)}
        tag="ul"
        unstyled={true}
      >
        <_Builtin.ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <_Builtin.DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            tag="div"
            delay={400}
            hover={true}
          >
            <_Builtin.DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              tag="div"
              data-state="expanded"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_links_text",
                  _activeStyleVariant
                )}
                tag="div"
              >
                {"Services"}
              </_Builtin.Block>
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_links_svg",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconArrow direction="Bottom" />
              </_Builtin.Block>
            </_Builtin.DropdownToggle>
            <_Builtin.DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_main_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_main_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "nav_dropdown_main_scroll",
                    _activeStyleVariant
                  )}
                  tag="div"
                  data-lenis-prevent=""
                >
                  <_Builtin.List
                    className={_utils.cx(
                      _styles,
                      "nav_dropdown_list",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-f898fa14-e9c4-646a-b332-c95900470b06-00470afa"
                    )}
                    tag="ul"
                    unstyled={false}
                  >
                    <_Builtin.ListItem
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_item",
                        _activeStyleVariant
                      )}
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_link",
                          _activeStyleVariant
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_text",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Branding"}
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.ListItem>
                    <_Builtin.ListItem
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_item",
                        _activeStyleVariant
                      )}
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_link",
                          _activeStyleVariant
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_text",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Website Design"}
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.ListItem>
                    <_Builtin.ListItem
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_item",
                        _activeStyleVariant
                      )}
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_link",
                          _activeStyleVariant
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_text",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Development"}
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.ListItem>
                  </_Builtin.List>
                </_Builtin.Block>
              </_Builtin.Block>
            </_Builtin.DropdownList>
          </_Builtin.DropdownWrapper>
        </_Builtin.ListItem>
        <_Builtin.ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <_Builtin.DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            tag="div"
            delay={400}
            hover={true}
          >
            <_Builtin.DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              tag="div"
              data-state="expanded"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_links_text",
                  _activeStyleVariant
                )}
                tag="div"
              >
                {"Work"}
              </_Builtin.Block>
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_links_svg",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconArrow direction="Bottom" />
              </_Builtin.Block>
            </_Builtin.DropdownToggle>
            <_Builtin.DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_mega_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_mega_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "nav_dropdown_mega_scroll",
                    _activeStyleVariant
                  )}
                  tag="div"
                  data-lenis-prevent=""
                >
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "nav_dropdown_mega_contain",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_mega_layout",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      <_Builtin.List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b1f-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                      </_Builtin.List>
                      <_Builtin.List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b2c-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                      </_Builtin.List>
                      <_Builtin.List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b39-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                      </_Builtin.List>
                      <_Builtin.List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b46-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                        <_Builtin.ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <_Builtin.Link
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            button={false}
                            block="inline"
                            options={{
                              href: "#",
                            }}
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </_Builtin.Block>
                          </_Builtin.Link>
                        </_Builtin.ListItem>
                      </_Builtin.List>
                    </_Builtin.Block>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.Block>
            </_Builtin.DropdownList>
          </_Builtin.DropdownWrapper>
        </_Builtin.ListItem>
        <_Builtin.ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <_Builtin.Link
            className={_utils.cx(
              _styles,
              "nav_links_link",
              _activeStyleVariant
            )}
            button={false}
            block="inline"
            options={{
              href: "#",
            }}
          >
            <_Builtin.Block
              className={_utils.cx(
                _styles,
                "nav_links_text",
                _activeStyleVariant
              )}
              tag="div"
            >
              {"About"}
            </_Builtin.Block>
          </_Builtin.Link>
        </_Builtin.ListItem>
        <_Builtin.ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <_Builtin.Link
            className={_utils.cx(
              _styles,
              "nav_links_link",
              _activeStyleVariant
            )}
            button={false}
            block="inline"
            options={{
              href: "#",
            }}
          >
            <_Builtin.Block
              className={_utils.cx(
                _styles,
                "nav_links_text",
                _activeStyleVariant
              )}
              tag="div"
            >
              {"Contact"}
            </_Builtin.Block>
          </_Builtin.Link>
        </_Builtin.ListItem>
      </_Builtin.List>
      <_Builtin.List
        className={_utils.cx(_styles, "nav_actions_wrap", _activeStyleVariant)}
        tag="ul"
        unstyled={true}
      >
        <_Builtin.ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <_Builtin.DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            tag="div"
            delay={400}
            hover={false}
          >
            <_Builtin.DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              tag="div"
              data-state="expanded"
            >
              <_Builtin.NotSupported _atom="LocalesWrapper" />
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_links_svg",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconArrow direction="Bottom" />
              </_Builtin.Block>
            </_Builtin.DropdownToggle>
            <_Builtin.DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_main_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_main_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <_Builtin.NotSupported _atom="LocalesWrapper" />
              </_Builtin.Block>
            </_Builtin.DropdownList>
          </_Builtin.DropdownWrapper>
        </_Builtin.ListItem>
        <_Builtin.ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <_Builtin.DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            tag="div"
            data-open-on-mobile=""
            delay={400}
            hover={false}
          >
            <_Builtin.DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              tag="div"
              data-state="expanded"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_links_search_icon",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconSearch />
              </_Builtin.Block>
              <_Builtin.Block
                className={_utils.cx(_styles, "u-sr-only", _activeStyleVariant)}
                tag="div"
              >
                {"Search"}
              </_Builtin.Block>
            </_Builtin.DropdownToggle>
            <_Builtin.DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_mega_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_mega_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "nav_dropdown_mega_scroll",
                    _activeStyleVariant
                  )}
                  tag="div"
                  data-lenis-prevent=""
                >
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "nav_dropdown_mega_contain",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <_Builtin.SearchForm
                      className={_utils.cx(
                        _styles,
                        "nav_search_wrap",
                        _activeStyleVariant
                      )}
                      action="/search"
                      role="search"
                      data-trigger="focus"
                    >
                      <_Builtin.DOM
                        className={_utils.cx(
                          _styles,
                          "nav_search_btn_wrap",
                          _activeStyleVariant
                        )}
                        tag="button"
                        slot=""
                        type="submit"
                        tabindex="-1"
                      >
                        <_Builtin.DOM
                          className={_utils.cx(
                            _styles,
                            "nav_search_btn_icon",
                            _activeStyleVariant
                          )}
                          tag="svg"
                          slot=""
                          xmlns="http://www.w3.org/2000/svg"
                          width="100%"
                          viewBox="0 0 400 400"
                          fill="none"
                          aria-hidden="true"
                        >
                          <_Builtin.DOM
                            tag="circle"
                            slot=""
                            cx="171"
                            cy="171"
                            r="155"
                            stroke="currentColor"
                            stroke-width="var(--nav--icon-thickness)"
                            vector-effect="non-scaling-stroke"
                          />
                          <_Builtin.DOM
                            tag="path"
                            slot=""
                            d="M280.602 280.602L388.602 388.602"
                            stroke="currentColor"
                            stroke-width="var(--nav--icon-thickness)"
                            vector-effect="non-scaling-stroke"
                          />
                        </_Builtin.DOM>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "nav_screen-reader-text",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Search"}
                        </_Builtin.Block>
                      </_Builtin.DOM>
                      <_Builtin.DOM
                        className={_utils.cx(
                          _styles,
                          "nav_search_label",
                          _activeStyleVariant
                        )}
                        tag="label"
                        slot=""
                      >
                        <_Builtin.DOM
                          className={_utils.cx(
                            _styles,
                            "nav_screen-reader-text",
                            _activeStyleVariant
                          )}
                          tag="span"
                          slot=""
                        >
                          {"Search"}
                        </_Builtin.DOM>
                        <_Builtin.SearchInput
                          className={_utils.cx(
                            _styles,
                            "nav_search_field",
                            _activeStyleVariant
                          )}
                          placeholder="Search…"
                          autoFocus={false}
                          disabled={false}
                          maxLength={256}
                          name="query"
                          required={true}
                          type="search"
                          id="search"
                        />
                      </_Builtin.DOM>
                    </_Builtin.SearchForm>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.Block>
            </_Builtin.DropdownList>
          </_Builtin.DropdownWrapper>
        </_Builtin.ListItem>
        <_Builtin.ListItem
          className={_utils.cx(
            _styles,
            "nav_buttons_item",
            "is-main",
            _activeStyleVariant
          )}
        >
          <ButtonMain style="Secondary" />
        </_Builtin.ListItem>
        <_Builtin.ListItem
          className={_utils.cx(
            _styles,
            "nav_buttons_item",
            _activeStyleVariant
          )}
        >
          <ButtonMain style="Primary" />
        </_Builtin.ListItem>
      </_Builtin.List>
    </_Component>
  );
}
